// <auto-generated />
namespace SPARSHBUILDCON.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfdfdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdfdf));
        
        string IMigrationMetadata.Id
        {
            get { return "202010191200581_dfdfdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
