// <auto-generated />
namespace SPARSHBUILDCON.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dfdfd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfdfd));
        
        string IMigrationMetadata.Id
        {
            get { return "202010200543354_dfdfd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
