// <auto-generated />
namespace SPARSHBUILDCON.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adcolpaidstatusinagdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adcolpaidstatusinagdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202012241123225_adcolpaidstatusinagdetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
